import React, { useState, useRef } from 'react';
import { motion, AnimatePresence } from 'motion/react';
import {
  Sparkles,
  Play,
  Eye,
  Calendar,
  Clock,
  Filter,
  ArrowUpRight,
  Search,
  Plus,
  Trash2,
  Upload,
  CloudUpload,
  Loader2,
  X,
  Image as ImageIcon,
  FlaskConical,
  Lock,
  KeyRound,
  ShieldCheck,
  Wand2,
  Zap,
  CheckCheck,
  ListOrdered,
  Atom,
  HelpCircle,
  Tag,
  Layers,
  Globe,
  Camera
} from 'lucide-react';
import { GALLERY_ITEMS } from '../data/mockData';
import { GalleryItem } from '../types';
import { uploadFileToFirebaseStorage, STORAGE_FOLDERS } from '../lib/firebase';
import { PhotoChangerModal } from './Modals/PhotoChangerModal';
import {
  generateLabExperimentFromTitle,
  LAB_CATEGORY_SUGGESTIONS,
  LAB_BADGE_SUGGESTIONS,
  QUICK_LAB_EXPERIMENT_PRESETS
} from '../lib/chemistryAutoGenerator';

const ADMIN_AUTH_KEY = 'kelaspakhafiz_admin_auth';
const DEFAULT_ADMIN_PASSCODE = 'hafiz2026';

const PRESET_LAB_IMAGES = [
  { label: 'Indikator Tabung', url: 'https://images.unsplash.com/photo-1532187863486-abf9dbad1b69?auto=format&fit=crop&w=800&q=80' },
  { label: 'Lab & Beaker', url: 'https://images.unsplash.com/photo-1518152006812-edab29b069ac?auto=format&fit=crop&w=800&q=80' },
  { label: 'Larutan Warna', url: 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=800&q=80' },
  { label: 'Mikroskop & Uji', url: 'https://images.unsplash.com/photo-1579154204601-01588f351e67?auto=format&fit=crop&w=800&q=80' },
  { label: 'Buret & Titrasi', url: 'https://images.unsplash.com/photo-1603555501671-8f96b3fce8b4?auto=format&fit=crop&w=800&q=80' },
  { label: 'Eksperimen Siswa', url: 'https://images.unsplash.com/photo-1532094349884-543bc11b234d?auto=format&fit=crop&w=800&q=80' },
];

interface GallerySectionProps {
  onSelectItem: (item: GalleryItem) => void;
  items?: GalleryItem[];
  isAdmin?: boolean;
  setIsAdmin?: (val: boolean) => void;
  onAddItem?: (item: GalleryItem) => void;
  onDeleteItem?: (itemId: string) => void;
  onUpdateItem?: (updatedItem: GalleryItem) => void;
  onAddToast?: (title: string, description?: string, type?: 'success' | 'info') => void;
}

export const GallerySection: React.FC<GallerySectionProps> = ({
  onSelectItem,
  items = GALLERY_ITEMS,
  isAdmin = false,
  setIsAdmin,
  onAddItem,
  onDeleteItem,
  onUpdateItem,
  onAddToast = (_t: string, _d?: string, _ty?: 'success' | 'info') => {}
}) => {
  const [selectedCategory, setSelectedCategory] = useState<string>('Semua');
  const [searchQuery, setSearchQuery] = useState<string>('');

  // Quick photo changer state
  const [itemForPhotoChange, setItemForPhotoChange] = useState<GalleryItem | null>(null);

  // Admin Passcode Modal
  const [isAdminModalOpen, setIsAdminModalOpen] = useState(false);
  const [passcodeAttempt, setPasscodeAttempt] = useState('');
  const [passcodeError, setPasscodeError] = useState(false);

  // Upload Photo Modal state
  const [isUploadModalOpen, setIsUploadModalOpen] = useState(false);
  const [formTitle, setFormTitle] = useState('');
  const [formCategory, setFormCategory] = useState<string>('Indikator Alami');
  const [formBadge, setFormBadge] = useState('Praktikum Siswa');
  const [formConcept, setFormConcept] = useState('');
  const [formDescription, setFormDescription] = useState('');
  const [formSteps, setFormSteps] = useState<string[]>([
    '1. Siapkan peralatan gelas dan larutan sampel uji.',
    '2. Lakukan pengujian dan amati perubahan warna / reaksi yang terjadi.',
    '3. Catat data hasil pengamatan dan simpulkan hasil praktikum.'
  ]);
  const [formMaterials, setFormMaterials] = useState<string[]>([
    'Peralatan gelas laboratorium (tabung reaksi, pipet tetes, plat tetes)',
    'Sampel zat uji dan pereaksi standar'
  ]);
  const [formResults, setFormResults] = useState('Reaksi kimia teramati dan terdata dengan baik.');
  const [formImageUrl, setFormImageUrl] = useState('');
  const [isUploading, setIsUploading] = useState(false);
  const [uploadProgress, setUploadProgress] = useState(0);
  const [itemToDelete, setItemToDelete] = useState<GalleryItem | null>(null);

  // Auto-generation & Suggestions State
  const [isAutoFillEnabled, setIsAutoFillEnabled] = useState(true);
  const [autoGeneratedNotice, setAutoGeneratedNotice] = useState<string | null>(null);
  const [showCategorySuggestions, setShowCategorySuggestions] = useState(false);
  const [isAdvancedStepsOpen, setIsAdvancedStepsOpen] = useState(false);

  const fileInputRef = useRef<HTMLInputElement | null>(null);

  const handleAdminLogin = (e: React.FormEvent) => {
    e.preventDefault();
    if (passcodeAttempt.trim() === DEFAULT_ADMIN_PASSCODE || passcodeAttempt.trim() === 'admin123' || passcodeAttempt.trim() === 'hafiz2026') {
      if (setIsAdmin) setIsAdmin(true);
      localStorage.setItem(ADMIN_AUTH_KEY, 'true');
      setIsAdminModalOpen(false);
      setPasscodeAttempt('');
      setPasscodeError(false);
      setIsUploadModalOpen(true);
      onAddToast('Mode Pengajar Aktif', 'Selamat datang Pak Hafiz! Silakan unggah foto dokumentasi lab.', 'success');
    } else {
      setPasscodeError(true);
      onAddToast('Passcode Salah', 'Passcode guru tidak cocok. Gunakan hafiz2026.', 'info');
    }
  };

  // Derive unique categories including custom ones
  const dynamicCategories = Array.from(
    new Set(['Semua', 'Indikator Alami', 'Eksperimen Lab', 'Karya Siswa', ...items.map((i) => i.category)])
  );

  const filteredItems = items.filter((item) => {
    const matchesCategory = selectedCategory === 'Semua' || item.category === selectedCategory;
    const matchesSearch =
      item.title.toLowerCase().includes(searchQuery.toLowerCase()) ||
      item.description.toLowerCase().includes(searchQuery.toLowerCase()) ||
      item.chemistryConcept.toLowerCase().includes(searchQuery.toLowerCase()) ||
      item.category.toLowerCase().includes(searchQuery.toLowerCase());
    return matchesCategory && matchesSearch;
  });

  // Filter category suggestions based on manual input
  const matchingCategorySuggestions = LAB_CATEGORY_SUGGESTIONS.filter((cat) =>
    cat.toLowerCase().includes(formCategory.toLowerCase())
  );

  // Trigger lab experiment content auto-generation from title
  const handleAutoGenerateLabContent = (customTitle?: string, overrideCategory?: string, overrideBadge?: string) => {
    const titleToUse = customTitle !== undefined ? customTitle : formTitle;
    if (!titleToUse.trim()) {
      onAddToast('Ketik Judul Terlebih Dahulu', 'Masukkan judul eksperimen lab untuk membuat deskripsi & prosedur otomatis.', 'info');
      return;
    }

    const result = generateLabExperimentFromTitle(
      titleToUse,
      overrideCategory || formCategory,
      overrideBadge || formBadge
    );

    setFormDescription(result.description);
    setFormConcept(result.chemistryConcept);
    setFormSteps(result.steps);
    setFormMaterials(result.materials);
    setFormResults(result.results);
    if (result.category) setFormCategory(result.category);
    if (result.badge) setFormBadge(result.badge);

    setAutoGeneratedNotice('✨ Deskripsi, prosedur praktikum, dan konsep reaksi berhasil dibuat otomatis!');
    onAddToast('Auto-Generate Lab Selesai', `Prosedur & konsep untuk "${titleToUse.slice(0, 30)}..." telah diisi otomatis.`, 'success');
    setTimeout(() => setAutoGeneratedNotice(null), 4000);
  };

  // Handle title input change with real-time auto-fill
  const handleTitleChangeWithAutoFill = (newTitle: string) => {
    setFormTitle(newTitle);

    if (isAutoFillEnabled) {
      if (newTitle.trim().length >= 3) {
        const result = generateLabExperimentFromTitle(newTitle, formCategory, formBadge);
        setFormDescription(result.description);
        setFormConcept(result.chemistryConcept);
        setFormSteps(result.steps);
        setFormMaterials(result.materials);
        setFormResults(result.results);
        if (result.category && (formCategory === 'Indikator Alami' || formCategory === 'Eksperimen Lab')) {
          setFormCategory(result.category);
        }
        if (result.badge) {
          setFormBadge(result.badge);
        }
        setAutoGeneratedNotice('⚡ Deskripsi, prosedur, & reaksi disinkronkan otomatis');
      } else if (newTitle.trim().length === 0) {
        setFormDescription('');
        setFormConcept('');
        setAutoGeneratedNotice(null);
      }
    }
  };

  // Apply a 1-click lab preset
  const handleApplyLabPreset = (preset: typeof QUICK_LAB_EXPERIMENT_PRESETS[0]) => {
    setFormTitle(preset.title);
    setFormCategory(preset.category);
    setFormBadge(preset.badge);

    const result = generateLabExperimentFromTitle(preset.title, preset.category, preset.badge);
    setFormDescription(result.description);
    setFormConcept(result.chemistryConcept);
    setFormSteps(result.steps);
    setFormMaterials(result.materials);
    setFormResults(result.results);

    setAutoGeneratedNotice(`✨ Topik ${preset.iconLabel} diaktifkan otomatis!`);
    onAddToast('Eksperimen Lab Dimuat', `Prosedur, reaksi, dan materi ${preset.iconLabel} berhasil diisi.`, 'success');
    setTimeout(() => setAutoGeneratedNotice(null), 3500);
  };

  // Step item handlers
  const handleAddStep = () => {
    setFormSteps([...formSteps, `${formSteps.length + 1}. `]);
  };

  const handleUpdateStep = (index: number, val: string) => {
    const updated = [...formSteps];
    updated[index] = val;
    setFormSteps(updated);
  };

  const handleRemoveStep = (index: number) => {
    if (formSteps.length <= 1) return;
    setFormSteps(formSteps.filter((_, i) => i !== index));
  };

  const handleFileUpload = async (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;

    if (!file.type.startsWith('image/')) {
      onAddToast('Format Tidak Didukung', 'Harap pilih file gambar (JPG, PNG, WebP).', 'info');
      return;
    }

    if (file.size > 10 * 1024 * 1024) {
      onAddToast('Ukuran Terlalu Besar', 'Maksimal ukuran foto adalah 10MB.', 'info');
      return;
    }

    setIsUploading(true);
    setUploadProgress(10);

    try {
      const downloadUrl = await uploadFileToFirebaseStorage(
        file,
        STORAGE_FOLDERS.GALLERY_IMAGES,
        (progress) => setUploadProgress(progress)
      );
      setFormImageUrl(downloadUrl);
      onAddToast('Foto Lab Terunggah', 'Foto berhasil disimpan di Firebase Storage (catatan_foto/galeri).', 'success');
    } catch (err) {
      console.warn('Firebase Storage upload error:', err);
      const reader = new FileReader();
      reader.onload = (event) => {
        setFormImageUrl(event.target?.result as string);
        onAddToast('Foto Disimpan Lokal', 'Foto tersimpan untuk pengunggahan.', 'info');
      };
      reader.readAsDataURL(file);
    } finally {
      setIsUploading(false);
      setUploadProgress(0);
      e.target.value = '';
    }
  };

  const handleSavePhoto = (e: React.FormEvent) => {
    e.preventDefault();
    if (!formTitle.trim()) {
      onAddToast('Judul Diperlukan', 'Harap isi judul eksperimen.', 'info');
      return;
    }
    if (!formImageUrl) {
      onAddToast('Foto Diperlukan', 'Harap unggah foto dokumentasi praktikum atau pilih foto sampel terlebih dahulu.', 'info');
      return;
    }

    const now = new Date();
    const dateFormatted = `${now.getDate()} ${
      ['Jan', 'Feb', 'Mar', 'Apr', 'Mei', 'Jun', 'Jul', 'Agu', 'Sep', 'Okt', 'Nov', 'Des'][now.getMonth()]
    } ${now.getFullYear()}`;

    const cleanSteps = formSteps.filter((s) => s.trim().length > 0);
    const cleanMaterials = formMaterials.filter((m) => m.trim().length > 0);

    const newItem: GalleryItem = {
      id: `gal-${Date.now()}`,
      title: formTitle.trim(),
      category: (formCategory.trim() || 'Eksperimen Lab') as any,
      badge: formBadge.trim() || 'Praktikum Kimia',
      image: formImageUrl,
      chemistryConcept: formConcept.trim() || 'Eksperimen & Reaksi Kimia',
      description: formDescription.trim() || 'Dokumentasi kegiatan praktikum siswa di laboratorium kimia SMA.',
      date: dateFormatted,
      materials: cleanMaterials.length > 0 ? cleanMaterials : ['Peralatan gelas lab', 'Sampel bahan uji'],
      steps: cleanSteps.length > 0 ? cleanSteps : ['Persiapan alat dan bahan', 'Pengamatan perubahan reaksi', 'Pencatatan data pengamatan'],
      results: formResults.trim() || 'Reaksi teramati dan terdokumentasi dengan baik.'
    };

    if (onAddItem) {
      onAddItem(newItem);
    }

    setIsUploadModalOpen(false);
    setFormTitle('');
    setFormConcept('');
    setFormDescription('');
    setFormImageUrl('');
    setAutoGeneratedNotice(null);
    onAddToast('Dokumentasi Ditambahkan', `Foto "${newItem.title}" tersimpan di Firebase Firestore & Storage.`, 'success');
  };

  return (
    <section id="galeri" className="py-20 bg-[#F4F8FC]">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        
        {/* Section Header */}
        <div className="flex flex-col md:flex-row md:items-end justify-between mb-12 gap-6">
          <div>
            <div className="inline-flex items-center gap-1.5 px-3.5 py-1 rounded-full bg-white border border-[#E2E8F0] text-[#0F172A] text-xs font-semibold mb-3 shadow-2xs">
              <Sparkles className="w-3.5 h-3.5 text-[#0284C7]" />
              <span className="uppercase tracking-widest text-[10px] text-[#0284C7] font-bold">Dokumentasi Praktik & Media</span>
            </div>
            <h2 className="text-3xl sm:text-4xl font-light font-heading text-[#0F172A] tracking-tight">
              Galeri <span className="font-semibold text-[#0284C7]">Praktikum</span>
            </h2>
            <p className="text-[#64748B] text-sm sm:text-base mt-2 max-w-xl">
              Dokumentasi nyata kegiatan praktikum kimia siswa. Dari uji indikator alami dapur hingga titrasi presisi laboratorium.
            </p>
          </div>

          <div className="flex items-center gap-3 w-full md:w-auto">
            {/* Search bar */}
            <div className="relative w-full md:w-72">
              <Search className="w-4 h-4 text-[#0284C7] absolute left-3.5 top-1/2 -translate-y-1/2" />
              <input
                type="text"
                value={searchQuery}
                onChange={(e) => setSearchQuery(e.target.value)}
                placeholder="Cari eksperimen (kunyit, titrasi)..."
                className="w-full pl-9 pr-4 py-2.5 text-xs sm:text-sm rounded-full bg-white border border-[#E2E8F0] focus:outline-none focus:border-[#0284C7] focus:ring-1 focus:ring-[#0284C7] text-[#0F172A] placeholder:text-[#94A3B8] shadow-2xs transition-all"
              />
            </div>

            {/* Upload Photo Button */}
            {isAdmin ? (
              <button
                onClick={() => {
                  setIsUploadModalOpen(true);
                  setAutoGeneratedNotice(null);
                }}
                className="px-4 py-2.5 rounded-full bg-[#0284C7] hover:bg-[#0369A1] text-white text-xs font-bold flex items-center gap-2 transition-all shadow-xs shrink-0 cursor-pointer"
              >
                <Plus className="w-4 h-4" />
                <span className="hidden sm:inline">Unggah Foto Lab</span>
              </button>
            ) : (
              <button
                onClick={() => setIsAdminModalOpen(true)}
                className="px-4 py-2.5 rounded-full bg-white hover:bg-[#E0F2FE] text-[#0284C7] border border-[#38BDF8] text-xs font-bold flex items-center gap-2 transition-all shadow-2xs shrink-0 cursor-pointer group"
                title="Unggah foto kegiatan praktikum lab (Mode Pengajar)"
              >
                <Plus className="w-4 h-4 text-[#0284C7]" />
                <span className="hidden sm:inline">Unggah Foto (Guru)</span>
              </button>
            )}
          </div>
        </div>

        {/* Category Filters */}
        <div className="flex items-center gap-2 overflow-x-auto pb-4 mb-8 scrollbar-none">
          {dynamicCategories.map((cat) => {
            const isActive = selectedCategory === cat;
            return (
              <button
                key={cat}
                onClick={() => setSelectedCategory(cat)}
                className={`px-4 py-2 rounded-full text-xs font-semibold whitespace-nowrap transition-all duration-200 cursor-pointer ${
                  isActive
                    ? 'bg-[#0284C7] text-white shadow-xs'
                    : 'bg-white text-[#64748B] hover:bg-[#E0F2FE] hover:text-[#0284C7] border border-[#E2E8F0]'
                }`}
              >
                {cat}
              </button>
            );
          })}
        </div>

        {/* Cards Grid */}
        <motion.div
          layout
          className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6 sm:gap-8"
        >
          <AnimatePresence>
            {filteredItems.map((item) => (
              <motion.article
                layout
                key={item.id}
                initial={{ opacity: 0, y: 15 }}
                animate={{ opacity: 1, y: 0 }}
                exit={{ opacity: 0, scale: 0.95 }}
                transition={{ duration: 0.3 }}
                className="group relative bg-white rounded-[24px] overflow-hidden border border-[#E2E8F0] shadow-[0_4px_24px_rgba(2,132,199,0.06)] hover:shadow-lg hover:border-[#0284C7]/40 transition-all duration-300 flex flex-col justify-between cursor-pointer transform hover:-translate-y-1"
              >
                {/* Image Container */}
                <div
                  onClick={() => onSelectItem(item)}
                  className="relative aspect-16/10 w-full overflow-hidden bg-[#E2E8F0]"
                >
                  <img
                    src={item.image}
                    alt={item.title}
                    referrerPolicy="no-referrer"
                    className="w-full h-full object-cover group-hover:scale-105 transition-transform duration-500"
                  />
                  <div className="absolute inset-0 bg-linear-to-t from-[#0F172A]/75 via-transparent to-transparent opacity-75 group-hover:opacity-85 transition-opacity" />
                  
                  {/* Category Chip */}
                  <span className="absolute top-3.5 left-3.5 px-3 py-1 text-[11px] font-bold uppercase tracking-wider rounded-full bg-white/90 text-[#0F172A] backdrop-blur-xs shadow-xs border border-white/60">
                    {item.category}
                  </span>

                  {/* Badge & Teacher Photo Changer */}
                  <div className="absolute top-3.5 right-3.5 flex items-center gap-1.5 z-10">
                    {isAdmin && (
                      <button
                        type="button"
                        onClick={(e) => {
                          e.stopPropagation();
                          setItemForPhotoChange(item);
                        }}
                        className="px-3 py-1.5 rounded-full bg-white/95 hover:bg-[#0284C7] text-[#0284C7] hover:text-white border border-[#BAE6FD] hover:border-[#0284C7] text-[11px] font-bold backdrop-blur-xs shadow-md transition-all flex items-center gap-1.5 cursor-pointer transform hover:scale-105"
                        title="Ganti / Cari Foto via Google atau Unggah dari HP/Laptop"
                      >
                        <Camera className="w-3.5 h-3.5" />
                        <span>Ganti / Cari Foto</span>
                      </button>
                    )}
                    <span className="px-3 py-1 text-[11px] font-medium rounded-full bg-[#0F172A]/80 text-white backdrop-blur-xs">
                      {item.badge}
                    </span>
                  </div>

                  {/* Video Duration if available */}
                  {item.videoDuration && (
                    <div className="absolute bottom-3 right-3 flex items-center gap-1 px-2.5 py-0.5 rounded-md bg-black/60 text-white text-[11px] backdrop-blur-xs font-mono">
                      <Play className="w-3 h-3 fill-white" />
                      <span>{item.videoDuration}</span>
                    </div>
                  )}
                </div>

                {/* Content Details */}
                <div className="p-6 flex-1 flex flex-col justify-between">
                  <div onClick={() => onSelectItem(item)}>
                    <div className="flex items-center gap-2 text-xs text-[#64748B] mb-2">
                      <Calendar className="w-3.5 h-3.5 text-[#0284C7]" />
                      <span>{item.date}</span>
                    </div>

                    <h3 className="text-base font-bold font-heading text-[#0F172A] leading-snug group-hover:text-[#0284C7] transition-colors mb-2 line-clamp-2">
                      {item.title}
                    </h3>

                    <p className="text-xs text-[#64748B] leading-relaxed line-clamp-2 mb-4">
                      {item.description}
                    </p>
                  </div>

                  <div className="pt-3.5 border-t border-[#E2E8F0] flex items-center justify-between">
                    <button
                      onClick={() => onSelectItem(item)}
                      className="text-xs font-semibold text-[#0284C7] group-hover:underline flex items-center gap-1 cursor-pointer"
                    >
                      Lihat Prosedur & Data
                      <ArrowUpRight className="w-3.5 h-3.5" />
                    </button>
                    
                    <div className="flex items-center gap-1.5">
                      <button
                        onClick={(e) => {
                          e.stopPropagation();
                          setItemForPhotoChange(item);
                        }}
                        className="p-2 rounded-full bg-[#F4F8FC] text-[#64748B] hover:bg-[#E0F2FE] hover:text-[#0284C7] transition-colors cursor-pointer"
                        title="Ganti Foto Praktikum (Upload / Cari Google)"
                      >
                        <ImageIcon className="w-4 h-4" />
                      </button>

                      {isAdmin && (
                        <button
                          onClick={(e) => {
                            e.stopPropagation();
                            setItemToDelete(item);
                          }}
                          className="p-1.5 rounded-full bg-[#FEE2E2] text-[#EF4444] hover:bg-[#EF4444] hover:text-white transition-colors cursor-pointer"
                          title="Hapus Foto Praktikum"
                        >
                          <Trash2 className="w-3.5 h-3.5" />
                        </button>
                      )}
                      <button
                        onClick={() => onSelectItem(item)}
                        className="p-2 rounded-full bg-[#F4F8FC] text-[#64748B] group-hover:bg-[#E0F2FE] group-hover:text-[#0284C7] transition-colors"
                        title="Buka Sub Tampilan Praktikum"
                      >
                        <Eye className="w-4 h-4" />
                      </button>
                    </div>
                  </div>
                </div>
              </motion.article>
            ))}
          </AnimatePresence>
        </motion.div>

        {filteredItems.length === 0 && (
          <div className="text-center py-16 bg-white rounded-[24px] border border-[#E2E8F0] p-8">
            <p className="text-[#64748B] text-sm">
              Tidak ada dokumentasi yang cocok dengan kata kunci "{searchQuery}".
            </p>
            <button
              onClick={() => {
                setSearchQuery('');
                setSelectedCategory('Semua');
              }}
              className="mt-3 px-5 py-2 text-xs font-bold text-white bg-[#0284C7] rounded-full"
            >
              Reset Pencarian
            </button>
          </div>
        )}

      </div>

      {/* Upload New Lab Photo Modal */}
      <AnimatePresence>
        {isUploadModalOpen && (
          <div className="fixed inset-0 z-50 flex items-center justify-center p-3 sm:p-4 overflow-y-auto">
            <motion.div
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              exit={{ opacity: 0 }}
              onClick={() => setIsUploadModalOpen(false)}
              className="fixed inset-0 bg-black/60 backdrop-blur-xs"
            />
            <motion.div
              initial={{ opacity: 0, scale: 0.95, y: 15 }}
              animate={{ opacity: 1, scale: 1, y: 0 }}
              exit={{ opacity: 0, scale: 0.95, y: 15 }}
              className="relative w-full max-w-2xl bg-white rounded-[28px] shadow-2xl border border-[#CBD5E1] p-5 sm:p-7 max-h-[92vh] overflow-y-auto z-10 my-auto"
            >
              {/* Modal Header */}
              <div className="flex items-center justify-between pb-3.5 border-b border-[#E2E8F0] mb-4">
                <div className="flex items-center gap-2.5">
                  <div className="w-9 h-9 rounded-full bg-[#E0F2FE] flex items-center justify-center text-[#0284C7] shadow-xs">
                    <FlaskConical className="w-5 h-5" />
                  </div>
                  <div>
                    <h3 className="text-base font-bold text-[#0F172A] font-heading flex items-center gap-2">
                      <span>Unggah Foto Eksperimen Lab</span>
                      <span className="px-2 py-0.5 rounded-full bg-[#E0F2FE] text-[#0369A1] text-[10px] font-bold">
                        Mode Pengajar
                      </span>
                    </h3>
                    <p className="text-xs text-[#64748B]">Dokumentasi praktikum dengan pembuatan deskripsi & reaksi otomatis</p>
                  </div>
                </div>
                <button
                  onClick={() => setIsUploadModalOpen(false)}
                  className="p-2 rounded-full hover:bg-[#F1F5F9] text-[#64748B] transition-colors cursor-pointer"
                >
                  <X className="w-4 h-4" />
                </button>
              </div>

              {/* Smart Auto-Generate Feature Banner */}
              <div className="p-3.5 rounded-2xl bg-linear-to-r from-[#F0F9FF] to-[#E0F2FE] border border-[#BAE6FD] mb-4 shadow-2xs">
                <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-2.5 mb-2.5">
                  <div className="flex items-center gap-2">
                    <div className="w-7 h-7 rounded-xl bg-[#0284C7] text-white flex items-center justify-center shadow-xs shrink-0">
                      <Wand2 className="w-4 h-4" />
                    </div>
                    <div>
                      <h4 className="text-xs font-bold text-[#0369A1] flex items-center gap-1.5">
                        <span>Fitur Cerdas Otomatis Dokumentasi Lab</span>
                        <span className="px-1.5 py-0.2 rounded bg-white text-[#0284C7] text-[10px] font-extrabold">AI Lab</span>
                      </h4>
                      <p className="text-[11px] text-[#0F172A]/70">
                        Ketik judul praktikum atau pilih topik di bawah untuk mengisi deskripsi, prosedur singkat, & reaksi kimia otomatis!
                      </p>
                    </div>
                  </div>

                  <button
                    type="button"
                    onClick={() => setIsAutoFillEnabled(!isAutoFillEnabled)}
                    className={`px-3 py-1.5 rounded-full text-xs font-bold flex items-center gap-1.5 transition-all self-start sm:self-auto cursor-pointer ${
                      isAutoFillEnabled
                        ? 'bg-[#0284C7] text-white shadow-xs'
                        : 'bg-white text-[#64748B] border border-[#CBD5E1]'
                    }`}
                  >
                    <Zap className={`w-3.5 h-3.5 ${isAutoFillEnabled ? 'fill-white text-white' : 'text-[#64748B]'}`} />
                    <span>{isAutoFillEnabled ? 'Auto-Generate Aktif' : 'Manual'}</span>
                  </button>
                </div>

                {/* Quick 1-Click Lab Presets */}
                <div className="pt-2 border-t border-[#BAE6FD]/70">
                  <span className="text-[10px] font-bold text-[#0369A1] uppercase tracking-wider block mb-1.5">
                    ⚡ Pilihan Cepat Eksperimen Kimia Populer:
                  </span>
                  <div className="flex items-center gap-1.5 overflow-x-auto pb-1 scrollbar-none">
                    {QUICK_LAB_EXPERIMENT_PRESETS.map((preset, idx) => (
                      <button
                        key={idx}
                        type="button"
                        onClick={() => handleApplyLabPreset(preset)}
                        className="px-2.5 py-1 rounded-lg bg-white hover:bg-[#0284C7] text-[#0369A1] hover:text-white text-[11px] font-semibold transition-all border border-[#BAE6FD] whitespace-nowrap shadow-2xs cursor-pointer flex items-center gap-1 shrink-0"
                        title={preset.title}
                      >
                        <span>{preset.iconLabel}</span>
                      </button>
                    ))}
                  </div>
                </div>

                {autoGeneratedNotice && (
                  <div className="mt-2 text-[11px] font-bold text-[#0369A1] bg-white/80 px-2.5 py-1 rounded-md border border-[#BAE6FD] flex items-center gap-1.5 animate-fadeIn">
                    <CheckCheck className="w-3.5 h-3.5 text-[#0284C7]" />
                    <span>{autoGeneratedNotice}</span>
                  </div>
                )}
              </div>

              <form onSubmit={handleSavePhoto} className="space-y-4 text-xs">
                {/* Judul Praktikum */}
                <div>
                  <div className="flex items-center justify-between mb-1">
                    <label className="block text-xs font-bold text-[#0F172A]">
                      Judul Praktikum / Eksperimen <span className="text-[#EF4444]">*</span>
                    </label>
                    <button
                      type="button"
                      onClick={() => handleAutoGenerateLabContent()}
                      className="px-2.5 py-1 rounded-md bg-[#E0F2FE] hover:bg-[#0284C7] text-[#0369A1] hover:text-white text-[11px] font-bold flex items-center gap-1 transition-all cursor-pointer border border-[#BAE6FD]"
                      title="Isi otomatis deskripsi, prosedur, dan konsep reaksi kimia dari judul"
                    >
                      <Wand2 className="w-3.5 h-3.5" />
                      <span>✨ Buat Otomatis dari Judul</span>
                    </button>
                  </div>
                  <input
                    type="text"
                    required
                    value={formTitle}
                    onChange={(e) => handleTitleChangeWithAutoFill(e.target.value)}
                    placeholder="Contoh: Identifikasi Asam Basa dengan Ekstrak Kunyit & Telang"
                    className="w-full px-3.5 py-2.5 rounded-xl bg-[#F8FAFC] border border-[#CBD5E1] text-[#0F172A] font-semibold focus:outline-none focus:border-[#0284C7] focus:ring-1 focus:ring-[#0284C7] transition-all"
                  />
                </div>

                {/* Kategori Manual dengan Suggestion & Badge */}
                <div className="grid grid-cols-1 sm:grid-cols-2 gap-3.5">
                  {/* Category with Manual Input + Interactive Suggestions */}
                  <div className="relative">
                    <div className="flex items-center justify-between mb-1">
                      <label className="block text-xs font-bold text-[#0F172A] flex items-center gap-1">
                        <Tag className="w-3.5 h-3.5 text-[#0284C7]" />
                        <span>Kategori Eksperimen</span>
                      </label>
                      <span className="text-[10px] text-[#64748B]">Bisa diketik manual</span>
                    </div>

                    <input
                      type="text"
                      value={formCategory}
                      onChange={(e) => {
                        setFormCategory(e.target.value);
                        setShowCategorySuggestions(true);
                      }}
                      onFocus={() => setShowCategorySuggestions(true)}
                      onBlur={() => setTimeout(() => setShowCategorySuggestions(false), 250)}
                      placeholder="Ketik kategori atau pilih saran..."
                      className="w-full px-3 py-2 rounded-xl bg-[#F8FAFC] border border-[#CBD5E1] text-[#0F172A] focus:outline-none focus:border-[#0284C7] focus:ring-1 focus:ring-[#0284C7]"
                    />

                    {/* Filtered suggestions popup when typing */}
                    {showCategorySuggestions && matchingCategorySuggestions.length > 0 && (
                      <div className="absolute top-full left-0 right-0 mt-1 bg-white rounded-xl shadow-xl border border-[#CBD5E1] p-1.5 z-30 max-h-48 overflow-y-auto">
                        <span className="text-[10px] font-bold text-[#64748B] px-2 py-0.5 block uppercase tracking-wider">
                          Saran Kategori Kimia:
                        </span>
                        {matchingCategorySuggestions.map((cat, i) => (
                          <button
                            key={i}
                            type="button"
                            onMouseDown={(e) => {
                              e.preventDefault();
                              setFormCategory(cat);
                              setShowCategorySuggestions(false);
                            }}
                            className="w-full text-left px-2.5 py-1.5 rounded-lg text-xs hover:bg-[#E0F2FE] hover:text-[#0284C7] text-[#0F172A] flex items-center justify-between transition-colors"
                          >
                            <span>{cat}</span>
                            {formCategory === cat && <CheckCheck className="w-3.5 h-3.5 text-[#0284C7]" />}
                          </button>
                        ))}
                      </div>
                    )}

                    {/* Suggestion Chips Below */}
                    <div className="mt-1.5 flex items-center gap-1 overflow-x-auto pb-0.5 scrollbar-none">
                      <span className="text-[10px] text-[#64748B] font-semibold shrink-0">Saran:</span>
                      {LAB_CATEGORY_SUGGESTIONS.slice(0, 5).map((cat, i) => (
                        <button
                          key={i}
                          type="button"
                          onClick={() => setFormCategory(cat)}
                          className={`px-2 py-0.5 rounded text-[10px] font-semibold shrink-0 transition-all cursor-pointer ${
                            formCategory === cat
                              ? 'bg-[#0284C7] text-white'
                              : 'bg-[#F1F5F9] text-[#475569] hover:bg-[#E0F2FE] hover:text-[#0284C7]'
                          }`}
                        >
                          {cat}
                        </button>
                      ))}
                    </div>
                  </div>

                  {/* Badge Label */}
                  <div>
                    <label className="block text-xs font-bold text-[#0F172A] mb-1 flex items-center gap-1">
                      <Layers className="w-3.5 h-3.5 text-[#0284C7]" />
                      <span>Badge Label Foto</span>
                    </label>
                    <input
                      type="text"
                      value={formBadge}
                      onChange={(e) => setFormBadge(e.target.value)}
                      placeholder="Contoh: Praktikum Siswa"
                      className="w-full px-3 py-2 rounded-xl bg-[#F8FAFC] border border-[#CBD5E1] text-[#0F172A] focus:outline-none focus:border-[#0284C7] focus:ring-1 focus:ring-[#0284C7]"
                    />
                    <div className="mt-1.5 flex items-center gap-1 overflow-x-auto pb-0.5 scrollbar-none">
                      <span className="text-[10px] text-[#64748B] font-semibold shrink-0">Pilihan:</span>
                      {LAB_BADGE_SUGGESTIONS.slice(0, 4).map((badge, i) => (
                        <button
                          key={i}
                          type="button"
                          onClick={() => setFormBadge(badge)}
                          className={`px-2 py-0.5 rounded text-[10px] font-semibold shrink-0 transition-all cursor-pointer ${
                            formBadge === badge
                              ? 'bg-[#0284C7] text-white'
                              : 'bg-[#F1F5F9] text-[#475569] hover:bg-[#E0F2FE] hover:text-[#0284C7]'
                          }`}
                        >
                          {badge}
                        </button>
                      ))}
                    </div>
                  </div>
                </div>

                {/* Konsep Kimia / Reaksi (Otomatis & Editable) */}
                <div>
                  <div className="flex items-center justify-between mb-1">
                    <label className="block text-xs font-bold text-[#0F172A] flex items-center gap-1.5">
                      <Atom className="w-3.5 h-3.5 text-[#0284C7]" />
                      <span>Konsep Kimia / Reaksi Setara <span className="text-[#0284C7] font-semibold text-[10px]">(Auto-Generated)</span></span>
                    </label>
                    <span className="text-[10px] text-[#64748B]">Prinsip & Persamaan Reaksi</span>
                  </div>
                  <textarea
                    rows={2}
                    value={formConcept}
                    onChange={(e) => setFormConcept(e.target.value)}
                    placeholder="Contoh: Pergeseran kesetimbangan ionisasi kurkuminoid. HCl(aq) + NaOH(aq) → NaCl(aq) + H₂O(l)"
                    className="w-full px-3.5 py-2 rounded-xl bg-[#F8FAFC] border border-[#CBD5E1] text-[#0F172A] font-mono text-[11px] leading-relaxed focus:outline-none focus:border-[#0284C7]"
                  />
                </div>

                {/* Deskripsi & Prosedur Singkat */}
                <div>
                  <div className="flex items-center justify-between mb-1">
                    <label className="block text-xs font-bold text-[#0F172A] flex items-center gap-1.5">
                      <FlaskConical className="w-3.5 h-3.5 text-[#0284C7]" />
                      <span>Deskripsi Tujuan & Ringkasan Praktikum <span className="text-[#0284C7] font-semibold text-[10px]">(Auto-Generated)</span></span>
                    </label>
                  </div>
                  <textarea
                    rows={3}
                    value={formDescription}
                    onChange={(e) => setFormDescription(e.target.value)}
                    placeholder="Jelaskan secara singkat tujuan eksperimen dan fenomena reaksi yang diamati..."
                    className="w-full px-3.5 py-2 rounded-xl bg-[#F8FAFC] border border-[#CBD5E1] text-[#0F172A] leading-relaxed focus:outline-none focus:border-[#0284C7]"
                  />
                </div>

                {/* Prosedur Singkat & Langkah Kerja Detail (Collapsible / Expandable) */}
                <div className="p-3.5 rounded-2xl bg-[#F8FAFC] border border-[#E2E8F0]">
                  <div className="flex items-center justify-between mb-2">
                    <label className="text-xs font-bold text-[#0F172A] flex items-center gap-1.5">
                      <ListOrdered className="w-3.5 h-3.5 text-[#0284C7]" />
                      <span>Prosedur Singkat & Langkah Kerja ({formSteps.length} Langkah)</span>
                    </label>
                    <button
                      type="button"
                      onClick={() => setIsAdvancedStepsOpen(!isAdvancedStepsOpen)}
                      className="text-[11px] font-bold text-[#0284C7] hover:underline cursor-pointer"
                    >
                      {isAdvancedStepsOpen ? 'Tutup Rincian' : 'Edit Rincian Langkah'}
                    </button>
                  </div>

                  {isAdvancedStepsOpen ? (
                    <div className="space-y-2 mt-2">
                      {formSteps.map((step, idx) => (
                        <div key={idx} className="flex items-center gap-2">
                          <span className="w-5 h-5 rounded-full bg-[#E0F2FE] text-[#0284C7] font-bold text-[10px] flex items-center justify-center shrink-0">
                            {idx + 1}
                          </span>
                          <input
                            type="text"
                            value={step}
                            onChange={(e) => handleUpdateStep(idx, e.target.value)}
                            className="flex-1 px-3 py-1.5 rounded-lg bg-white border border-[#CBD5E1] text-[#0F172A] text-xs"
                          />
                          {formSteps.length > 1 && (
                            <button
                              type="button"
                              onClick={() => handleRemoveStep(idx)}
                              className="p-1 rounded text-[#94A3B8] hover:text-[#EF4444] transition-colors"
                            >
                              <X className="w-3.5 h-3.5" />
                            </button>
                          )}
                        </div>
                      ))}
                      <button
                        type="button"
                        onClick={handleAddStep}
                        className="mt-1 px-3 py-1 rounded-lg bg-[#E0F2FE] text-[#0284C7] hover:bg-[#0284C7] hover:text-white text-[11px] font-bold flex items-center gap-1 transition-all"
                      >
                        <Plus className="w-3 h-3" />
                        <span>Tambah Langkah Kerja</span>
                      </button>
                    </div>
                  ) : (
                    <div className="text-[11px] text-[#64748B] space-y-1">
                      {formSteps.slice(0, 3).map((step, idx) => (
                        <p key={idx} className="truncate">• {step}</p>
                      ))}
                      {formSteps.length > 3 && (
                        <p className="text-[10px] text-[#0284C7] font-semibold">
                          +{formSteps.length - 3} langkah lainnya (klik 'Edit Rincian Langkah' untuk melihat semua)
                        </p>
                      )}
                    </div>
                  )}
                </div>

                {/* Upload Image Section + Quick Presets */}
                <div className="space-y-2.5 p-3.5 rounded-2xl bg-[#F8FAFC] border border-[#E2E8F0]">
                  <div className="flex items-center justify-between">
                    <label className="text-xs font-bold text-[#0F172A] flex items-center gap-1.5">
                      <ImageIcon className="w-3.5 h-3.5 text-[#0284C7]" />
                      <span>Foto Dokumentasi Lab <span className="text-[#EF4444]">*</span></span>
                    </label>
                    <input
                      type="file"
                      ref={fileInputRef}
                      onChange={handleFileUpload}
                      accept="image/*"
                      className="hidden"
                    />
                    <button
                      type="button"
                      disabled={isUploading}
                      onClick={() => fileInputRef.current?.click()}
                      className="text-xs font-bold text-[#0284C7] hover:underline flex items-center gap-1 cursor-pointer"
                    >
                      <CloudUpload className="w-3.5 h-3.5" />
                      <span>{isUploading ? 'Mengunggah...' : 'Pilih Foto dari Perangkat'}</span>
                    </button>
                  </div>

                  {isUploading && (
                    <div className="p-3 rounded-xl bg-[#E0F2FE] border border-[#0284C7]/30 flex items-center gap-2">
                      <Loader2 className="w-4 h-4 text-[#0284C7] animate-spin shrink-0" />
                      <div className="flex-grow">
                        <div className="w-full bg-[#BAE6FD] h-2 rounded-full overflow-hidden">
                          <div className="bg-[#0284C7] h-full transition-all duration-300" style={{ width: `${uploadProgress}%` }} />
                        </div>
                      </div>
                      <span className="text-[10px] font-bold text-[#0369A1]">{uploadProgress}%</span>
                    </div>
                  )}

                  {formImageUrl ? (
                    <div className="relative w-full h-40 rounded-xl overflow-hidden border border-[#CBD5E1] bg-black/5 shadow-inner">
                      <img src={formImageUrl} alt="Pratinjau Foto" referrerPolicy="no-referrer" className="w-full h-full object-cover" />
                      <button
                        type="button"
                        onClick={() => setFormImageUrl('')}
                        className="absolute top-2 right-2 p-1.5 rounded-full bg-black/70 text-white hover:bg-[#EF4444] transition-colors"
                        title="Hapus foto"
                      >
                        <X className="w-4 h-4" />
                      </button>
                      <div className="absolute bottom-2 left-2 px-2.5 py-1 rounded-md bg-black/70 text-white text-[10px] font-bold backdrop-blur-xs">
                        Foto Terpasang
                      </div>
                    </div>
                  ) : (
                    <div
                      onClick={() => fileInputRef.current?.click()}
                      className="w-full h-24 rounded-xl border-2 border-dashed border-[#CBD5E1] hover:border-[#0284C7] bg-white flex flex-col items-center justify-center gap-1 cursor-pointer p-3 text-center transition-colors"
                    >
                      <Upload className="w-5 h-5 text-[#0284C7]" />
                      <span className="font-semibold text-[#0F172A] text-xs">Klik untuk Unggah Foto Praktikum</span>
                      <span className="text-[10px] text-[#94A3B8]">Disimpan otomatis ke Firebase Storage (catatan_foto/galeri)</span>
                    </div>
                  )}

                  {/* Sample Chemistry Lab Images (Quick Pick) */}
                  <div className="pt-1.5 border-t border-[#E2E8F0]">
                    <span className="text-[10px] font-bold text-[#64748B] block mb-1">
                      Atau Pilih Foto Sampel Laboratorium Instan:
                    </span>
                    <div className="grid grid-cols-3 sm:grid-cols-6 gap-1.5">
                      {PRESET_LAB_IMAGES.map((img, idx) => (
                        <button
                          key={idx}
                          type="button"
                          onClick={() => {
                            setFormImageUrl(img.url);
                            onAddToast('Foto Sampel Dipilih', `Foto sampel "${img.label}" terpasang.`, 'info');
                          }}
                          className={`group relative h-12 rounded-lg overflow-hidden border transition-all cursor-pointer ${
                            formImageUrl === img.url
                              ? 'border-[#0284C7] ring-2 ring-[#0284C7]'
                              : 'border-[#CBD5E1] hover:border-[#0284C7]'
                          }`}
                        >
                          <img src={img.url} alt={img.label} referrerPolicy="no-referrer" className="w-full h-full object-cover group-hover:scale-110 transition-transform" />
                          <span className="absolute inset-x-0 bottom-0 bg-black/70 text-white text-[9px] truncate px-1 py-0.5 text-center">
                            {img.label}
                          </span>
                        </button>
                      ))}
                    </div>
                  </div>
                </div>

                {/* Modal Footer Actions */}
                <div className="flex items-center justify-end gap-2 pt-3 border-t border-[#E2E8F0]">
                  <button
                    type="button"
                    onClick={() => setIsUploadModalOpen(false)}
                    className="px-4 py-2 rounded-full border border-[#CBD5E1] text-[#64748B] hover:bg-[#F1F5F9] font-semibold transition-colors cursor-pointer"
                  >
                    Batal
                  </button>
                  <button
                    type="submit"
                    disabled={isUploading}
                    className="px-5 py-2 rounded-full bg-[#0284C7] hover:bg-[#0369A1] text-white font-bold shadow-xs disabled:opacity-50 flex items-center gap-1.5 transition-all cursor-pointer"
                  >
                    <CloudUpload className="w-4 h-4" />
                    <span>Simpan ke Cloud Firestore</span>
                  </button>
                </div>
              </form>
            </motion.div>
          </div>
        )}
      </AnimatePresence>

      {/* Delete Confirmation Modal */}
      <AnimatePresence>
        {itemToDelete && (
          <div className="fixed inset-0 z-50 flex items-center justify-center p-4">
            <motion.div
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              exit={{ opacity: 0 }}
              onClick={() => setItemToDelete(null)}
              className="fixed inset-0 bg-black/60 backdrop-blur-xs"
            />
            <motion.div
              initial={{ opacity: 0, scale: 0.95 }}
              animate={{ opacity: 1, scale: 1 }}
              exit={{ opacity: 0, scale: 0.95 }}
              className="relative w-full max-w-sm bg-white rounded-[24px] shadow-2xl border border-[#CBD5E1] p-6 z-10 text-center"
            >
              <div className="w-12 h-12 rounded-full bg-[#FEE2E2] text-[#EF4444] flex items-center justify-center mx-auto mb-3">
                <Trash2 className="w-6 h-6" />
              </div>
              <h3 className="text-base font-bold text-[#0F172A] mb-1">Hapus Foto Praktikum?</h3>
              <p className="text-xs text-[#64748B] mb-5">
                Foto "{itemToDelete.title}" akan dihapus permanen dari Firebase Firestore.
              </p>
              <div className="flex items-center justify-center gap-3">
                <button
                  onClick={() => setItemToDelete(null)}
                  className="px-4 py-2 rounded-full border border-[#CBD5E1] text-xs font-semibold text-[#64748B]"
                >
                  Batal
                </button>
                <button
                  onClick={() => {
                    if (onDeleteItem) {
                      onDeleteItem(itemToDelete.id);
                    }
                    onAddToast('Foto Dihapus', `Foto "${itemToDelete.title}" telah dihapus.`, 'info');
                    setItemToDelete(null);
                  }}
                  className="px-4 py-2 rounded-full bg-[#EF4444] hover:bg-[#DC2626] text-white text-xs font-bold shadow-xs"
                >
                  Hapus Permanen
                </button>
              </div>
            </motion.div>
          </div>
        )}
      </AnimatePresence>

      {/* Admin Passcode Modal for Teachers */}
      <AnimatePresence>
        {isAdminModalOpen && (
          <div className="fixed inset-0 z-50 flex items-center justify-center p-4">
            <motion.div
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              exit={{ opacity: 0 }}
              onClick={() => {
                setIsAdminModalOpen(false);
                setPasscodeError(false);
              }}
              className="fixed inset-0 bg-black/60 backdrop-blur-xs"
            />
            <motion.div
              initial={{ opacity: 0, scale: 0.95, y: 20 }}
              animate={{ opacity: 1, scale: 1, y: 0 }}
              exit={{ opacity: 0, scale: 0.95, y: 20 }}
              className="relative w-full max-w-sm bg-white rounded-[28px] shadow-2xl border border-[#CBD5E1] p-6 z-10"
            >
              <div className="text-center mb-5">
                <div className="w-12 h-12 rounded-full bg-[#E0F2FE] text-[#0284C7] flex items-center justify-center mx-auto mb-3 shadow-xs">
                  <KeyRound className="w-6 h-6" />
                </div>
                <h3 className="text-base font-bold text-[#0F172A]">Akses Guru Pak Hafiz</h3>
                <p className="text-xs text-[#64748B] mt-1">
                  Masukkan passcode pengajar untuk mengunggah foto dokumentasi eksperimen lab.
                </p>
              </div>

              <form onSubmit={handleAdminLogin} className="space-y-4">
                <div>
                  <label className="block text-xs font-bold text-[#0F172A] mb-1">Passcode Guru</label>
                  <input
                    type="password"
                    value={passcodeAttempt}
                    onChange={(e) => {
                      setPasscodeAttempt(e.target.value);
                      setPasscodeError(false);
                    }}
                    placeholder="Masukkan passcode..."
                    className={`w-full px-3.5 py-2.5 rounded-xl border text-sm text-center tracking-widest ${
                      passcodeError ? 'border-[#EF4444] bg-[#FEF2F2]' : 'border-[#CBD5E1] bg-[#F8FAFC]'
                    }`}
                    autoFocus
                  />
                  {passcodeError && (
                    <p className="text-[11px] text-[#EF4444] mt-1 font-medium text-center">
                      Passcode salah. Gunakan: <span className="font-bold">hafiz2026</span>
                    </p>
                  )}
                </div>

                <div className="flex items-center gap-2">
                  <button
                    type="button"
                    onClick={() => {
                      setIsAdminModalOpen(false);
                      setPasscodeError(false);
                    }}
                    className="w-1/2 py-2.5 rounded-full border border-[#CBD5E1] text-xs font-semibold text-[#64748B]"
                  >
                    Batal
                  </button>
                  <button
                    type="submit"
                    className="w-1/2 py-2.5 rounded-full bg-[#0284C7] hover:bg-[#0369A1] text-white text-xs font-bold shadow-xs"
                  >
                    Masuk
                  </button>
                </div>
              </form>
            </motion.div>
          </div>
        )}
      </AnimatePresence>

      {/* Quick Photo Changer Modal for Gallery Cards */}
      {itemForPhotoChange && (
        <PhotoChangerModal
          isOpen={!!itemForPhotoChange}
          onClose={() => setItemForPhotoChange(null)}
          currentImageUrl={itemForPhotoChange.image}
          itemTitle={itemForPhotoChange.title}
          onSavePhoto={(newUrl) => {
            if (onUpdateItem && itemForPhotoChange) {
              onUpdateItem({
                ...itemForPhotoChange,
                image: newUrl
              });
            }
            onAddToast('Foto Praktikum Diperbarui', 'Foto baru berhasil disimpan & diperbarui di Galeri.', 'success');
            setItemForPhotoChange(null);
          }}
          onAddToast={onAddToast}
        />
      )}
    </section>
  );
};

